### ISSUE TITLE
 '.data/paranmt/test.txt' is missing. 

### ISSUE THREAD

**Issue by c4n** [ghazi-f/QKVAE#1]
Hi,
I'm trying to reimplement your paper. However, there's a file missing from the GoogleDrive link.

FileNotFoundError: [Errno 2] No such file or directory: '.data/paranmt/test.txt'

**Comment by ghazi-f** [comment]
Hi,

Thank you for pointing it out. Those are dev and test files where sentences are paired with their paraphrases like in the train set.
I forgot they were not included in the original drive of Chen et al. Here is [the link to a drive where you can find these files](https://drive.google.com/drive/folders/1o5r8UBu8efXgN5vPjb3p622CJZDFPfwD?usp=sharing).

I will also add to the readme.

**Comment by c4n** [comment]
It works now. Thank  you!
